<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DzViewModule\Controller\Plugin\Factory\ViewModelFactory'       => __DIR__ . '/src/DzViewModule/Controller/Plugin/Factory/ViewModelFactory.php',
  'DzViewModule\Controller\Plugin\ViewModel'                      => __DIR__ . '/src/DzViewModule/Controller/Plugin/ViewModel.php',
  'DzViewModule\Exception\InvalidModelException'                  => __DIR__ . '/src/DzViewModule/Exception/InvalidModelException.php',
  'DzViewModule\Factory\PhpRendererStrategyFactory'               => __DIR__ . '/src/DzViewModule/Factory/PhpRendererStrategyFactory.php',
  'DzViewModule\Factory\ViewModelManagerFactory'                  => __DIR__ . '/src/DzViewModule/Factory/ViewModelManagerFactory.php',
  'DzViewModule\Listener\AddViewModelManagerListener'             => __DIR__ . '/src/DzViewModule/Listener/AddViewModelManagerListener.php',
  'DzViewModule\Listener\RegisterViewStrategyListener'            => __DIR__ . '/src/DzViewModule/Listener/RegisterViewStrategyListener.php',
  'DzViewModule\Module'                                           => __DIR__ . '/src/DzViewModule/Module.php',
  'DzViewModule\ModuleManager\Feature\ViewModelProviderInterface' => __DIR__ . '/src/DzViewModule/ModuleManager/Feature/ViewModelProviderInterface.php',
  'DzViewModule\View\Helper\Widget'                               => __DIR__ . '/src/DzViewModule/View/Helper/Widget.php',
  'DzViewModule\View\ModelPluginManager'                          => __DIR__ . '/src/DzViewModule/View/ModelPluginManager.php',
  'DzViewModule\View\ModelPluginManagerAwareInterface'            => __DIR__ . '/src/DzViewModule/View/ModelPluginManagerAwareInterface.php',
  'DzViewModule\View\Model\ModelInterface'                        => __DIR__ . '/src/DzViewModule/View/Model/ModelInterface.php',
  'DzViewModule\View\Model\ViewModel'                             => __DIR__ . '/src/DzViewModule/View/Model/ViewModel.php',
  'DzViewModule\View\Renderer\PhpRenderer'                        => __DIR__ . '/src/DzViewModule/View/Renderer/PhpRenderer.php',
  'DzViewModule\View\Strategy\PhpRendererStrategy'                => __DIR__ . '/src/DzViewModule/View/Strategy/PhpRendererStrategy.php',
);
